// <auto-generated />
using System;
using CardPlatform.MyDBModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CardPlatform.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20201010075759_initAddPermissionmodels")]
    partial class initAddPermissionmodels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("CardPlatform.Models.PermissionModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PermissionModelsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.Property<string>("URLName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PermissionModelsId");

                    b.ToTable("PermissionModels");
                });

            modelBuilder.Entity("CardPlatform.Models.UserInfo", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("LasLoginTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserName");

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("CardPlatform.Models.PermissionModels", b =>
                {
                    b.HasOne("CardPlatform.Models.PermissionModels", null)
                        .WithMany("ChlinPermissionModels")
                        .HasForeignKey("PermissionModelsId");
                });
#pragma warning restore 612, 618
        }
    }
}
